### PR TITLE
Fix deprecation warnings related to String.characters

### PR DESCRIPTION
**Pull request by florianreinhart**

### CODE REVIEW

**Comment by florianreinhart** [comment]
@kjessup @iamjono Could you merge this and release a new version?

**Comment by florianreinhart** [comment]
@kjessup @iamjono Could you merge this and release a new version?

**Comment by florianreinhart** [comment]
No idea why this doesn't get merged. For anyone else wanting to get rid of the deprecation warnings, just use my fork. I will keep the fork updated with upstream changes.

https://github.com/florianreinhart/Perfect-Zip

**Review by Coeur — APPROVED** [review]

**Comment by kjessup** [comment]
Yikes. My GitHub notifications were going to /dev/null or somewhere similar for a while. 
I've merged this and tagged it as 3.0.3. Better late than never, I hope.

Thank you.

**Pull request merged**
